#!/usr/bin/env python3
"""Generate feature-registry.md and next-work-queue.md from feature frontmatter.

Usage:
    python3 generate-indexes.py /path/to/repo
    python3 generate-indexes.py /path/to/repo --dry-run

Reads YAML frontmatter from docs/features/*.md, produces:
  - docs/generated/feature-registry.md
  - docs/generated/next-work-queue.md
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path


GENERATED_HEADER = "<!-- Generated by repo-memory. Do not edit directly. -->"

READY_ORDER = ["ready", "verify-first", "needs-human", "blocked"]

TERMINAL_STATUSES = {"shipped", "abandoned", "superseded", "deprecated", "rolled_back"}

REQUIRED_FIELDS = {"id", "title", "status", "ready", "next_safe_step"}


def parse_frontmatter(text: str) -> dict | None:
    """Parse YAML frontmatter from a markdown file. Returns None if missing."""
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return None
    fields: dict = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            # Handle numeric priority
            if key == "priority":
                try:
                    fields[key] = int(value)
                except ValueError:
                    fields[key] = None
            else:
                fields[key] = value
    return fields


def load_features(features_dir: Path) -> list[dict]:
    """Load all feature docs with valid frontmatter."""
    features = []
    if not features_dir.exists():
        return features

    for md_file in sorted(features_dir.glob("*.md")):
        if md_file.name.startswith("_"):
            continue
        text = md_file.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        if fm is None:
            continue
        # Check required fields
        if not REQUIRED_FIELDS.issubset(fm.keys()):
            continue
        fm["_file"] = md_file.name
        fm["_slug"] = md_file.stem
        features.append(fm)

    return features


def build_feature_registry(features: list[dict], generated_at: str) -> str:
    """Build the feature registry markdown table."""
    sorted_features = sorted(
        features,
        key=lambda f: (f.get("priority") or 999, f.get("id", "")),
    )

    lines = [
        GENERATED_HEADER,
        "",
        "# Feature Registry",
        "",
        f"> Generated: {generated_at}",
        "",
        "## Feature List",
        "",
        "| ID | Title | Status | Priority | Ready | Owner | Last Updated |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]

    for f in sorted_features:
        lines.append(
            f"| {f['id']} | {f['title']} | {f['status']} "
            f"| {f.get('priority', '—')} | {f['ready']} "
            f"| {f.get('owner', '—')} | {f.get('last_updated', '—')} |"
        )

    lines.append("")
    return "\n".join(lines)


def build_next_work_queue(features: list[dict], generated_at: str) -> str:
    """Build the next-work-queue markdown table."""
    actionable = [f for f in features if f["status"] not in TERMINAL_STATUSES]

    actionable.sort(
        key=lambda f: (
            READY_ORDER.index(f["ready"]) if f["ready"] in READY_ORDER else 99,
            f.get("priority") or 999,
            f.get("id", ""),
        )
    )

    lines = [
        GENERATED_HEADER,
        "",
        "# Next Work Queue",
        "",
        f"> Generated: {generated_at}",
        "",
    ]

    if not actionable:
        lines.append(
            "_No actionable features. All features are terminal or have invalid frontmatter._"
        )
        lines.append("")
        return "\n".join(lines)

    lines.extend([
        "| ID | Title | Status | Ready | Priority | Next Safe Step |",
        "| --- | --- | --- | --- | --- | --- |",
    ])

    for f in actionable:
        lines.append(
            f"| {f['id']} | {f['title']} | {f['status']} "
            f"| {f['ready']} | {f.get('priority', '—')} "
            f"| {f['next_safe_step']} |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate feature registry and work queue from frontmatter."
    )
    parser.add_argument(
        "repo",
        nargs="?",
        default=".",
        help="Path to the repository root (default: current directory)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be generated without writing files.",
    )
    parser.add_argument(
        "--features-dir",
        default="docs/features",
        help="Relative path to features directory (default: docs/features)",
    )
    parser.add_argument(
        "--output-dir",
        default="docs/generated",
        help="Relative path to generated output directory (default: docs/generated)",
    )
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    features_dir = repo / args.features_dir
    output_dir = repo / args.output_dir

    if not features_dir.exists():
        print(f"Features directory not found: {features_dir}", file=sys.stderr)
        print("Nothing to generate.", file=sys.stderr)
        return 0

    features = load_features(features_dir)

    if not features:
        print("No valid feature docs found (need YAML frontmatter with id, title, status, ready, next_safe_step).")
        return 0

    generated_at = date.today().isoformat()
    registry = build_feature_registry(features, generated_at)
    queue = build_next_work_queue(features, generated_at)

    registry_path = output_dir / "feature-registry.md"
    queue_path = output_dir / "next-work-queue.md"

    if args.dry_run:
        print(f"Would write: {registry_path}")
        print(f"Would write: {queue_path}")
        print(f"\nFeatures found: {len(features)}")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(registry, encoding="utf-8")
    queue_path.write_text(queue, encoding="utf-8")

    print(f"✓ {registry_path.relative_to(repo)}")
    print(f"✓ {queue_path.relative_to(repo)}")
    print(f"  ({len(features)} features)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
