import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { runAudit } from '../../src/commands/audit';

const CONFIG_YAML = `\
version: 3
mode: standard
docs_root: docs
paths:
  ownership_map: docs/README.md
  project_overview: docs/project-overview.md
  architecture: docs/architecture.md
  features: docs/features
  plans: docs/plans
  reviews: docs/reviews
  generated: docs/generated
  intake: docs/intake
  adr: docs/adr
  history: docs/history
  runbooks: docs/runbooks
generated:
  header: "<!-- Generated by repo-memory. Do not edit directly. -->"
  feature_registry: docs/generated/feature-registry.md
  next_work_queue: docs/generated/next-work-queue.md
  doc_health: docs/generated/doc-health.md
priority:
  lower_number_is_higher: true
compatibility:
  preserve_existing_agent_files: true
  use_managed_blocks: true
  allow_external_paths: true
  map_existing_plan_dirs: true
  map_existing_review_dirs: true
external_sources:
  docs: []
  plans: []
  reviews: []
ownership:
  capabilities:
    architecture:
      owner: docs/architecture.md
      type: local
adapters:
  installed: []
  available:
    - generic
validation:
  allow_manual_central_registry: false
  require_feature_frontmatter: true
  require_plan_frontmatter: false
  require_review_frontmatter: false
  require_evidence_for_inferred_claims: true
  warn_on_unmapped_plan_dirs: true
  warn_on_unmapped_review_dirs: true
  fail_on_generated_file_manual_edit: true
`;

const validFeatureFm = (slug: string, overrides: Record<string, unknown> = {}): string => {
  const fm = { id: slug, title: `Feature ${slug}`, status: 'planned', doc_type: 'feature', ready: 'ready', next_safe_step: 'Next step', ...overrides };
  const lines = Object.entries(fm).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join('\n');
  return `---\n${lines}\n---\n\n# Feature\n`;
};

const GENERATED_HEADER = '<!-- Generated by repo-memory. Do not edit directly. -->';
const CUSTOM_GENERATED_HEADER = '<!-- Custom generated header -->';

describe('runAudit', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'rm-audit-test-'));
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), CONFIG_YAML, 'utf8');
    fs.mkdirSync(path.join(tmpDir, 'docs', 'features'), { recursive: true });
    fs.mkdirSync(path.join(tmpDir, 'docs', 'plans'), { recursive: true });
    fs.mkdirSync(path.join(tmpDir, 'docs', 'reviews'), { recursive: true });
    fs.mkdirSync(path.join(tmpDir, 'docs', 'generated'), { recursive: true });
    // Create valid ownership map
    fs.writeFileSync(path.join(tmpDir, 'docs', 'README.md'), '# Docs\n', 'utf8');
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('passes with a clean repo (no features, no generated files)', () => {
    const result = runAudit(tmpDir);
    // No critical issues expected; only possible info about adapters
    expect(result.passed).toBe(true);
    expect(result.issues.filter((i) => i.severity === 'critical')).toHaveLength(0);
  });

  it('fails when config is missing', () => {
    fs.rmSync(path.join(tmpDir, 'repo-memory.config.yml'));
    const result = runAudit(tmpDir);
    expect(result.passed).toBe(false);
    expect(result.issues.some((i) => i.category === 'config')).toBe(true);
  });

  it('raises a critical issue for a feature missing frontmatter (when required)', () => {
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'bad.md'), '# No FM\n', 'utf8');
    const result = runAudit(tmpDir);
    expect(result.passed).toBe(false);
    expect(result.issues.some((i) => i.severity === 'critical' && i.category === 'feature-frontmatter')).toBe(true);
  });

  it('raises a critical issue for invalid feature schema', () => {
    const bad = validFeatureFm('bad', { status: 'bogus' });
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'bad.md'), bad, 'utf8');
    const result = runAudit(tmpDir);
    expect(result.passed).toBe(false);
    expect(result.issues.some((i) => i.severity === 'critical')).toBe(true);
  });

  it('raises a critical issue for duplicate feature IDs', () => {
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'f1.md'), validFeatureFm('same-id'), 'utf8');
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'f2.md'), validFeatureFm('same-id', { title: 'F2' }), 'utf8');
    const result = runAudit(tmpDir);
    expect(result.issues.some((i) => i.category === 'feature-duplicate')).toBe(true);
  });

  it('raises a critical issue when a generated file is manually edited', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'generated', 'feature-registry.md'),
      '# Manual edit — no generated header\n',
      'utf8'
    );
    const result = runAudit(tmpDir);
    expect(result.issues.some((i) => i.category === 'generated-file' && i.severity === 'critical')).toBe(true);
  });

  it('does not flag correctly-headered generated files', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'generated', 'feature-registry.md'),
      `${GENERATED_HEADER}\n\n# Feature Registry\n`,
      'utf8'
    );
    const result = runAudit(tmpDir);
    expect(result.issues.filter((i) => i.category === 'generated-file')).toHaveLength(0);
  });

  it('uses configured generated header when checking generated files', () => {
    const customConfig = CONFIG_YAML.replace(
      'header: "<!-- Generated by repo-memory. Do not edit directly. -->"',
      `header: "${CUSTOM_GENERATED_HEADER}"`
    );
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), customConfig, 'utf8');
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'generated', 'feature-registry.md'),
      `${CUSTOM_GENERATED_HEADER}\n\n# Feature Registry\n`,
      'utf8'
    );
    const result = runAudit(tmpDir);
    expect(result.issues.filter((i) => i.category === 'generated-file')).toHaveLength(0);
  });

  it('reports missing plan frontmatter as plan-frontmatter (not plan-schema) when optional', () => {
    fs.writeFileSync(path.join(tmpDir, 'docs', 'plans', 'no-frontmatter.md'), '# No FM\n', 'utf8');
    const result = runAudit(tmpDir);
    expect(result.issues.some((i) => i.category === 'plan-frontmatter' && i.severity === 'warning')).toBe(true);
    expect(result.issues.some((i) => i.category === 'plan-schema')).toBe(false);
  });

  it('reports missing plan frontmatter as critical when required', () => {
    const strictPlanConfig = CONFIG_YAML.replace(
      'require_plan_frontmatter: false',
      'require_plan_frontmatter: true'
    );
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), strictPlanConfig, 'utf8');
    fs.writeFileSync(path.join(tmpDir, 'docs', 'plans', 'no-frontmatter.md'), '# No FM\n', 'utf8');
    const result = runAudit(tmpDir);
    expect(result.issues.some((i) => i.category === 'plan-frontmatter' && i.severity === 'critical')).toBe(true);
  });

  it('reports missing review frontmatter as review-frontmatter (not review-schema) when optional', () => {
    fs.writeFileSync(path.join(tmpDir, 'docs', 'reviews', 'no-frontmatter.md'), '# No FM\n', 'utf8');
    const result = runAudit(tmpDir);
    expect(result.issues.some((i) => i.category === 'review-frontmatter' && i.severity === 'warning')).toBe(true);
    expect(result.issues.some((i) => i.category === 'review-schema')).toBe(false);
  });

  it('reports missing review frontmatter as critical when required', () => {
    const strictReviewConfig = CONFIG_YAML.replace(
      'require_review_frontmatter: false',
      'require_review_frontmatter: true'
    );
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), strictReviewConfig, 'utf8');
    fs.writeFileSync(path.join(tmpDir, 'docs', 'reviews', 'no-frontmatter.md'), '# No FM\n', 'utf8');
    const result = runAudit(tmpDir);
    expect(
      result.issues.some((i) => i.category === 'review-frontmatter' && i.severity === 'critical')
    ).toBe(true);
  });

  it('raises a warning when the ownership map is missing', () => {
    fs.rmSync(path.join(tmpDir, 'docs', 'README.md'));
    const result = runAudit(tmpDir);
    expect(result.issues.some((i) => i.category === 'ownership-map' && i.severity === 'warning')).toBe(true);
  });

  it('reports correct feature count in summary', () => {
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'f1.md'), validFeatureFm('f1'), 'utf8');
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'f2.md'), validFeatureFm('f2'), 'utf8');
    const result = runAudit(tmpDir);
    expect(result.summary.features).toBe(2);
  });

  it('passes when all features have valid frontmatter', () => {
    fs.writeFileSync(path.join(tmpDir, 'docs', 'features', 'good.md'), validFeatureFm('good'), 'utf8');
    const result = runAudit(tmpDir);
    // Only possible non-critical issues are adapter info
    expect(result.issues.filter((i) => i.severity === 'critical')).toHaveLength(0);
  });
});
