import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { loadConfig, validateConfig } from '../../src/core/config';

function mkdirp(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

const VALID_CONFIG = {
  version: 3 as const,
  mode: 'standard' as const,
  docs_root: 'docs',
  paths: {
    ownership_map: 'docs/README.md',
    project_overview: 'docs/project-overview.md',
    architecture: 'docs/architecture.md',
    features: 'docs/features',
    plans: 'docs/plans',
    reviews: 'docs/reviews',
    generated: 'docs/generated',
    intake: 'docs/intake',
    adr: 'docs/adr',
    history: 'docs/history',
    runbooks: 'docs/runbooks',
  },
  generated: {
    header: '<!-- Generated by repo-memory. Do not edit directly. -->',
    feature_registry: 'docs/generated/feature-registry.md',
    next_work_queue: 'docs/generated/next-work-queue.md',
    doc_health: 'docs/generated/doc-health.md',
  },
  priority: { lower_number_is_higher: true },
  compatibility: {
    preserve_existing_agent_files: true,
    use_managed_blocks: true,
    allow_external_paths: true,
    map_existing_plan_dirs: true,
    map_existing_review_dirs: true,
  },
  external_sources: { docs: [], plans: [], reviews: [] },
  ownership: {
    capabilities: {
      architecture: { owner: 'docs/architecture.md', type: 'local' as const },
    },
  },
  adapters: {
    installed: [],
    available: ['generic', 'claude-code'],
  },
  validation: {
    allow_manual_central_registry: false,
    require_feature_frontmatter: true,
    require_plan_frontmatter: false,
    require_review_frontmatter: false,
    require_evidence_for_inferred_claims: true,
    warn_on_unmapped_plan_dirs: true,
    warn_on_unmapped_review_dirs: true,
    fail_on_generated_file_manual_edit: true,
  },
};

describe('validateConfig', () => {
  it('accepts a valid config object', () => {
    const result = validateConfig(VALID_CONFIG);
    expect(result.version).toBe(3);
    expect(result.mode).toBe('standard');
  });

  it('rejects wrong version number', () => {
    const bad = { ...VALID_CONFIG, version: 2 };
    expect(() => validateConfig(bad)).toThrow('Configuration validation failed');
  });

  it('rejects invalid mode', () => {
    const bad = { ...VALID_CONFIG, mode: 'bogus' };
    expect(() => validateConfig(bad)).toThrow('Configuration validation failed');
  });

  it('rejects missing paths field', () => {
    const { paths: _, ...bad } = VALID_CONFIG;
    expect(() => validateConfig(bad)).toThrow('Configuration validation failed');
  });

  it('rejects missing required path key', () => {
    const bad = {
      ...VALID_CONFIG,
      paths: { ...VALID_CONFIG.paths, features: undefined },
    };
    expect(() => validateConfig(bad)).toThrow('Configuration validation failed');
  });

  it('rejects invalid capability type', () => {
    const bad = {
      ...VALID_CONFIG,
      ownership: {
        capabilities: {
          arch: { owner: 'docs/arch.md', type: 'wrong-type' },
        },
      },
    };
    expect(() => validateConfig(bad)).toThrow('Configuration validation failed');
  });
});

describe('loadConfig', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-memory-config-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('returns null when no config file exists', () => {
    const result = loadConfig(tmpDir);
    expect(result).toBeNull();
  });

  it('loads and validates a valid yml config', () => {
    const yaml = `
version: 3
mode: standard
docs_root: docs
paths:
  ownership_map: docs/README.md
  project_overview: docs/project-overview.md
  architecture: docs/architecture.md
  features: docs/features
  plans: docs/plans
  reviews: docs/reviews
  generated: docs/generated
  intake: docs/intake
  adr: docs/adr
  history: docs/history
  runbooks: docs/runbooks
generated:
  header: "<!-- Generated by repo-memory. Do not edit directly. -->"
  feature_registry: docs/generated/feature-registry.md
  next_work_queue: docs/generated/next-work-queue.md
  doc_health: docs/generated/doc-health.md
priority:
  lower_number_is_higher: true
compatibility:
  preserve_existing_agent_files: true
  use_managed_blocks: true
  allow_external_paths: true
  map_existing_plan_dirs: true
  map_existing_review_dirs: true
external_sources:
  docs: []
  plans: []
  reviews: []
ownership:
  capabilities:
    architecture:
      owner: docs/architecture.md
      type: local
adapters:
  installed: []
  available:
    - generic
validation:
  allow_manual_central_registry: false
  require_feature_frontmatter: true
  require_plan_frontmatter: false
  require_review_frontmatter: false
  require_evidence_for_inferred_claims: true
  warn_on_unmapped_plan_dirs: true
  warn_on_unmapped_review_dirs: true
  fail_on_generated_file_manual_edit: true
`;
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), yaml, 'utf8');
    const result = loadConfig(tmpDir);
    expect(result).not.toBeNull();
    expect(result!.version).toBe(3);
    expect(result!.paths.features).toBe('docs/features');
  });

  it('throws when config file is invalid YAML', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'repo-memory.config.yml'),
      ': invalid: yaml: [[[',
      'utf8'
    );
    expect(() => loadConfig(tmpDir)).toThrow();
  });

  it('throws when config has wrong version', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'repo-memory.config.yml'),
      'version: 2\nmode: standard\n',
      'utf8'
    );
    expect(() => loadConfig(tmpDir)).toThrow('Configuration validation failed');
  });
});
