import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { runGeneration } from '../../src/commands/generate';

const VALID_CONFIG_YAML = `\
version: 3
mode: standard
docs_root: docs
paths:
  ownership_map: docs/README.md
  project_overview: docs/project-overview.md
  architecture: docs/architecture.md
  features: docs/features
  plans: docs/plans
  reviews: docs/reviews
  generated: docs/generated
  intake: docs/intake
  adr: docs/adr
  history: docs/history
  runbooks: docs/runbooks
generated:
  header: "<!-- Generated by repo-memory. Do not edit directly. -->"
  feature_registry: docs/generated/feature-registry.md
  next_work_queue: docs/generated/next-work-queue.md
  doc_health: docs/generated/doc-health.md
priority:
  lower_number_is_higher: true
compatibility:
  preserve_existing_agent_files: true
  use_managed_blocks: true
  allow_external_paths: true
  map_existing_plan_dirs: true
  map_existing_review_dirs: true
external_sources:
  docs: []
  plans: []
  reviews: []
ownership:
  capabilities:
    architecture:
      owner: docs/architecture.md
      type: local
adapters:
  installed: []
  available:
    - generic
validation:
  allow_manual_central_registry: false
  require_feature_frontmatter: true
  require_plan_frontmatter: false
  require_review_frontmatter: false
  require_evidence_for_inferred_claims: true
  warn_on_unmapped_plan_dirs: true
  warn_on_unmapped_review_dirs: true
  fail_on_generated_file_manual_edit: true
`;

const validFeatureFm = (
  slug: string,
  overrides: Record<string, unknown> = {}
): string => {
  const fm = {
    id: slug,
    title: `Feature ${slug}`,
    status: 'planned',
    doc_type: 'feature',
    ready: 'ready',
    next_safe_step: 'Next step',
    priority: 1,
    ...overrides,
  };
  const lines = Object.entries(fm)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join('\n');
  return `---\n${lines}\n---\n\n# Feature\n`;
};

describe('runGeneration', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-memory-generate-test-'));
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), VALID_CONFIG_YAML, 'utf8');
    fs.mkdirSync(path.join(tmpDir, 'docs', 'features'), { recursive: true });
    fs.mkdirSync(path.join(tmpDir, 'docs', 'generated'), { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('returns an error when no config file is found', () => {
    fs.rmSync(path.join(tmpDir, 'repo-memory.config.yml'));
    const result = runGeneration(tmpDir);
    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors[0]).toContain('No repo-memory.config.yml');
  });

  it('generates three files with the correct paths', () => {
    const result = runGeneration(tmpDir);
    const paths = result.generated.map((f) => f.path);
    expect(paths.some((p) => p.endsWith('feature-registry.md'))).toBe(true);
    expect(paths.some((p) => p.endsWith('next-work-queue.md'))).toBe(true);
    expect(paths.some((p) => p.endsWith('doc-health.md'))).toBe(true);
  });

  it('includes the generated header in every file', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'feat-a.md'),
      validFeatureFm('feat-a'),
      'utf8'
    );
    const result = runGeneration(tmpDir);
    for (const file of result.generated) {
      expect(file.content).toContain('<!-- Generated by repo-memory. Do not edit directly. -->');
    }
  });

  it('feature-registry includes a feature row for each valid feature', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'feat-a.md'),
      validFeatureFm('feat-a', { title: 'Feature A' }),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'feat-b.md'),
      validFeatureFm('feat-b', { title: 'Feature B', priority: 2 }),
      'utf8'
    );
    const result = runGeneration(tmpDir);
    const registry = result.generated.find((f) => f.path.endsWith('feature-registry.md'))!;
    expect(registry.content).toContain('feat-a');
    expect(registry.content).toContain('feat-b');
    expect(registry.content).toContain('Feature A');
    expect(registry.content).toContain('Feature B');
  });

  it('next-work-queue excludes shipped and abandoned features', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'active.md'),
      validFeatureFm('active', { status: 'in_progress' }),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'done.md'),
      validFeatureFm('done', { status: 'shipped', ready: 'ready' }),
      'utf8'
    );
    const result = runGeneration(tmpDir);
    const queue = result.generated.find((f) => f.path.endsWith('next-work-queue.md'))!;
    expect(queue.content).toContain('active');
    expect(queue.content).not.toContain('| done');
  });

  it('next-work-queue sorts by readiness then priority', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'low-pri.md'),
      validFeatureFm('low-pri', { priority: 5, ready: 'ready' }),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'high-pri.md'),
      validFeatureFm('high-pri', { priority: 1, ready: 'ready' }),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'needs-human.md'),
      validFeatureFm('needs-human', { priority: 1, ready: 'needs-human' }),
      'utf8'
    );
    const result = runGeneration(tmpDir);
    const queue = result.generated.find((f) => f.path.endsWith('next-work-queue.md'))!;
    const highPriIdx = queue.content.indexOf('high-pri');
    const lowPriIdx = queue.content.indexOf('low-pri');
    const needsHumanIdx = queue.content.indexOf('needs-human');
    // ready features come before needs-human
    expect(highPriIdx).toBeLessThan(needsHumanIdx);
    // higher priority (lower number) comes before lower priority
    expect(highPriIdx).toBeLessThan(lowPriIdx);
  });

  it('doc-health includes the total and valid feature counts', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'good.md'),
      validFeatureFm('good'),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'bad.md'),
      '# No frontmatter\n',
      'utf8'
    );
    const result = runGeneration(tmpDir);
    const health = result.generated.find((f) => f.path.endsWith('doc-health.md'))!;
    expect(health.content).toContain('Total feature files: 2');
    expect(health.content).toContain('Valid (parseable frontmatter): 1');
    expect(health.content).toContain('Invalid or missing frontmatter: 1');
  });

  it('reports duplicate IDs as an error', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'dup.md'),
      validFeatureFm('dup-id'),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'dup2.md'),
      validFeatureFm('dup-id', { title: 'Dup2' }),
      'utf8'
    );
    const result = runGeneration(tmpDir);
    expect(result.errors.some((e) => e.includes('Duplicate'))).toBe(true);
  });

  it('generates deterministic output for the same inputs', () => {
    const slugs = ['c-feature', 'a-feature', 'b-feature'];
    for (const slug of slugs) {
      fs.writeFileSync(
        path.join(tmpDir, 'docs', 'features', `${slug}.md`),
        validFeatureFm(slug, { title: `Feature ${slug}` }),
        'utf8'
      );
    }
    const result1 = runGeneration(tmpDir);
    const result2 = runGeneration(tmpDir);
    for (let i = 0; i < result1.generated.length; i++) {
      // Strip the date line for determinism check (date is always today)
      const normalize = (s: string) => s.replace(/> Generated: .+/, '> Generated: DATE');
      expect(normalize(result1.generated[i].content)).toBe(
        normalize(result2.generated[i].content)
      );
    }
  });
});
