import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { buildMigrationPlan } from '../../src/commands/migrate';

const V3_CONFIG_YAML = `\
version: 3
mode: standard
docs_root: docs
paths:
  ownership_map: docs/README.md
  project_overview: docs/project-overview.md
  architecture: docs/architecture.md
  features: docs/features
  plans: docs/plans
  reviews: docs/reviews
  generated: docs/generated
  intake: docs/intake
  adr: docs/adr
  history: docs/history
  runbooks: docs/runbooks
generated:
  header: "<!-- Generated by repo-memory. Do not edit directly. -->"
  feature_registry: docs/generated/feature-registry.md
  next_work_queue: docs/generated/next-work-queue.md
  doc_health: docs/generated/doc-health.md
priority:
  lower_number_is_higher: true
compatibility:
  preserve_existing_agent_files: true
  use_managed_blocks: true
  allow_external_paths: true
  map_existing_plan_dirs: true
  map_existing_review_dirs: true
external_sources:
  docs: []
  plans: []
  reviews: []
ownership:
  capabilities:
    architecture:
      owner: docs/architecture.md
      type: local
adapters:
  installed: []
  available:
    - generic
validation:
  allow_manual_central_registry: false
  require_feature_frontmatter: true
  require_plan_frontmatter: false
  require_review_frontmatter: false
  require_evidence_for_inferred_claims: true
  warn_on_unmapped_plan_dirs: true
  warn_on_unmapped_review_dirs: true
  fail_on_generated_file_manual_edit: true
`;

describe('buildMigrationPlan', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'rm-migrate-test-'));
    // Create a .git directory so the repo is discovered properly
    fs.mkdirSync(path.join(tmpDir, '.git'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('warns when repo is not v2-style', () => {
    // No docs/, no SKILL.md — will be 'absent'
    const result = buildMigrationPlan(tmpDir);
    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.actions).toHaveLength(0);
  });

  it('detects v2 feature-registry.md and plans deprecation action', () => {
    fs.mkdirSync(path.join(tmpDir, 'docs'), { recursive: true });
    // v2 style: manual feature-registry.md at docs/feature-registry.md
    fs.writeFileSync(path.join(tmpDir, 'docs', 'feature-registry.md'), '# Feature Registry\n', 'utf8');
    // Also add SKILL.md to make discovery classify as v2-style
    fs.mkdirSync(path.join(tmpDir, 'skills', 'repo-memory'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, 'skills', 'repo-memory', 'SKILL.md'), '# SKILL\n', 'utf8');
    const result = buildMigrationPlan(tmpDir);
    // Should have a deprecate action for the feature registry
    expect(result.actions.some((a) => a.type === 'deprecate' && a.path.includes('feature-registry'))).toBe(true);
  });

  it('adds a create action for missing v3 config', () => {
    fs.mkdirSync(path.join(tmpDir, 'docs'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, 'docs', 'feature-registry.md'), '# Registry\n', 'utf8');
    fs.mkdirSync(path.join(tmpDir, 'skills', 'repo-memory'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, 'skills', 'repo-memory', 'SKILL.md'), '# SKILL\n', 'utf8');
    const result = buildMigrationPlan(tmpDir);
    expect(result.actions.some((a) => a.type === 'create' && a.path === 'repo-memory.config.yml')).toBe(true);
  });

  it('does not add a create-config action when config already exists', () => {
    fs.mkdirSync(path.join(tmpDir, 'docs'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, 'docs', 'feature-registry.md'), '# Registry\n', 'utf8');
    fs.mkdirSync(path.join(tmpDir, 'skills', 'repo-memory'), { recursive: true });
    fs.writeFileSync(path.join(tmpDir, 'skills', 'repo-memory', 'SKILL.md'), '# SKILL\n', 'utf8');
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), V3_CONFIG_YAML, 'utf8');
    const result = buildMigrationPlan(tmpDir);
    expect(result.actions.some((a) => a.type === 'create' && a.path === 'repo-memory.config.yml')).toBe(false);
  });

  it('includes fromVersion and toVersion', () => {
    const result = buildMigrationPlan(tmpDir);
    expect(result.toVersion).toBe('v3-style');
  });
});
