import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { runValidation } from '../../src/commands/validate';

// Minimal valid YAML config
const VALID_CONFIG_YAML = `\
version: 3
mode: standard
docs_root: docs
paths:
  ownership_map: docs/README.md
  project_overview: docs/project-overview.md
  architecture: docs/architecture.md
  features: docs/features
  plans: docs/plans
  reviews: docs/reviews
  generated: docs/generated
  intake: docs/intake
  adr: docs/adr
  history: docs/history
  runbooks: docs/runbooks
generated:
  header: "<!-- Generated by repo-memory. Do not edit directly. -->"
  feature_registry: docs/generated/feature-registry.md
  next_work_queue: docs/generated/next-work-queue.md
  doc_health: docs/generated/doc-health.md
priority:
  lower_number_is_higher: true
compatibility:
  preserve_existing_agent_files: true
  use_managed_blocks: true
  allow_external_paths: true
  map_existing_plan_dirs: true
  map_existing_review_dirs: true
external_sources:
  docs: []
  plans: []
  reviews: []
ownership:
  capabilities:
    architecture:
      owner: docs/architecture.md
      type: local
adapters:
  installed: []
  available:
    - generic
validation:
  allow_manual_central_registry: false
  require_feature_frontmatter: true
  require_plan_frontmatter: false
  require_review_frontmatter: false
  require_evidence_for_inferred_claims: true
  warn_on_unmapped_plan_dirs: true
  warn_on_unmapped_review_dirs: true
  fail_on_generated_file_manual_edit: true
`;

// Minimal valid feature frontmatter
const validFeatureFm = (slug: string, overrides: Record<string, unknown> = {}): string => {
  const fm = {
    id: slug,
    title: `Feature ${slug}`,
    status: 'planned',
    doc_type: 'feature',
    ready: 'ready',
    next_safe_step: 'Next step here',
    ...overrides,
  };
  const lines = Object.entries(fm)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join('\n');
  return `---\n${lines}\n---\n\n# Feature ${slug}\n`;
};

describe('runValidation', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-memory-validate-test-'));
    // Write the config file
    fs.writeFileSync(path.join(tmpDir, 'repo-memory.config.yml'), VALID_CONFIG_YAML, 'utf8');
    // Create the features directory
    fs.mkdirSync(path.join(tmpDir, 'docs', 'features'), { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('returns valid when no feature files exist', () => {
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(true);
    expect(result.featureCount).toBe(0);
    expect(result.errorCount).toBe(0);
  });

  it('returns valid for a single valid feature file', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'my-feature.md'),
      validFeatureFm('my-feature'),
      'utf8'
    );
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(true);
    expect(result.featureCount).toBe(1);
    expect(result.errorCount).toBe(0);
  });

  it('returns invalid when a feature file is missing frontmatter and require_feature_frontmatter is true', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'no-fm.md'),
      '# No Frontmatter\n\nBody.\n',
      'utf8'
    );
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(false);
    expect(result.errorCount).toBeGreaterThan(0);
    expect(result.issues.some((i) => i.message.includes('frontmatter'))).toBe(true);
  });

  it('does not fail when frontmatter is missing and require_feature_frontmatter is false', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'repo-memory.config.yml'),
      VALID_CONFIG_YAML.replace('require_feature_frontmatter: true', 'require_feature_frontmatter: false'),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'no-fm.md'),
      '# No Frontmatter\n\nBody.\n',
      'utf8'
    );

    const result = runValidation(tmpDir);
    expect(result.valid).toBe(true);
    expect(result.errorCount).toBe(0);
  });

  it('returns invalid when a feature file has an invalid status', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'bad.md'),
      validFeatureFm('bad', { status: 'bogus-status' }),
      'utf8'
    );
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(false);
    expect(result.issues.some((i) => i.message.toLowerCase().includes('status'))).toBe(true);
  });

  it('returns invalid when duplicate feature IDs are found', () => {
    const slug = 'dup-id';
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', `${slug}.md`),
      validFeatureFm(slug),
      'utf8'
    );
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'other.md'),
      validFeatureFm(slug, { title: 'Other Feature' }),  // same id, different file name
      'utf8'
    );
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(false);
    expect(result.issues.some((i) => i.message.includes('Duplicate'))).toBe(true);
  });

  it('returns error when no config file is found', () => {
    fs.rmSync(path.join(tmpDir, 'repo-memory.config.yml'));
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(false);
    expect(result.issues.some((i) => i.message.includes('No repo-memory.config.yml'))).toBe(true);
  });

  it('returns valid for multiple valid feature files', () => {
    const slugs = ['alpha', 'beta', 'gamma'];
    for (const slug of slugs) {
      fs.writeFileSync(
        path.join(tmpDir, 'docs', 'features', `${slug}.md`),
        validFeatureFm(slug),
        'utf8'
      );
    }
    const result = runValidation(tmpDir);
    expect(result.valid).toBe(true);
    expect(result.featureCount).toBe(3);
  });

  it('includes the file path in issue reports', () => {
    fs.writeFileSync(
      path.join(tmpDir, 'docs', 'features', 'broken.md'),
      '# No Frontmatter\n',
      'utf8'
    );
    const result = runValidation(tmpDir);
    expect(result.issues.some((i) => i.file.includes('broken.md'))).toBe(true);
  });
});
